# Generated by Django 4.2.24 on 2025-09-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS products_shop_translation (
                id SERIAL PRIMARY KEY,
                master_id INTEGER NOT NULL REFERENCES products_shop(id) ON DELETE CASCADE,
                language_code VARCHAR(15) NOT NULL,
                name VARCHAR(255),
                address TEXT,
                city VARCHAR(100),
                UNIQUE(master_id, language_code)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS products_shop_translation;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS products_category_translation (
                id SERIAL PRIMARY KEY,
                master_id INTEGER NOT NULL REFERENCES products_category(id) ON DELETE CASCADE,
                language_code VARCHAR(15) NOT NULL,
                name VARCHAR(255) NOT NULL,
                description TEXT,
                UNIQUE(master_id, language_code)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS products_category_translation;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS products_tag_translation (
                id SERIAL PRIMARY KEY,
                master_id INTEGER NOT NULL REFERENCES products_tag(id) ON DELETE CASCADE,
                language_code VARCHAR(15) NOT NULL,
                name VARCHAR(255) NOT NULL,
                UNIQUE(master_id, language_code)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS products_tag_translation;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS products_product_translation (
                id SERIAL PRIMARY KEY,
                master_id INTEGER NOT NULL REFERENCES products_product(id) ON DELETE CASCADE,
                language_code VARCHAR(15) NOT NULL,
                name VARCHAR(255) NOT NULL,
                description TEXT,
                UNIQUE(master_id, language_code)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS products_product_translation;"
        ),
    ]
