# Generated by Django 4.2.24 on 2025-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Адрес магазина',
                'verbose_name_plural': 'Адреса магазинов',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_addresses',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('sales_executive', 'Менеджер'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_addresses',
            field=models.ManyToManyField(blank=True, to='products.shopaddress', verbose_name='Адреса магазинов'),
        ),
    ]
