# Generated by Django 4.2.24 on 2025-09-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_create_shop_translations'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE products_shop ALTER COLUMN name DROP NOT NULL;
            ALTER TABLE products_shop ALTER COLUMN address DROP NOT NULL;
            ALTER TABLE products_shop ALTER COLUMN city DROP NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE products_shop ALTER COLUMN name SET NOT NULL;
            ALTER TABLE products_shop ALTER COLUMN address SET NOT NULL;
            ALTER TABLE products_shop ALTER COLUMN city SET NOT NULL;
            """
        ),
    ]
