# Generated by Django 4.2.24 on 2025-09-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shopaddress_user_phone_number_and_more'),
    ]

    operations = [
    ]
