# Generated by Django 4.2.24 on 2025-09-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_make_shop_name_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE products_category ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
            ALTER TABLE products_category ADD COLUMN IF NOT EXISTS show_in_megamenu BOOLEAN DEFAULT FALSE;
            ALTER TABLE products_category ADD COLUMN IF NOT EXISTS icon VARCHAR(50);
            """,
            reverse_sql="""
            ALTER TABLE products_category DROP COLUMN IF EXISTS sort_order;
            ALTER TABLE products_category DROP COLUMN IF EXISTS show_in_megamenu;
            ALTER TABLE products_category DROP COLUMN IF EXISTS icon;
            """
        ),
    ]
