# Generated by Django 4.2.24 on 2025-09-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_banner_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='product_banners/', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('style', models.CharField(choices=[('discount', 'Скидка'), ('new', 'Новинка'), ('popular', 'Популярное'), ('premium', 'Премиум'), ('sale', 'Распродажа'), ('delivery', 'Доставка')], default='new', max_length=20, verbose_name='Стиль баннера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('button_text', models.CharField(default='Подробнее', max_length=50, verbose_name='Текст кнопки')),
                ('background_color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет текста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товарный баннер',
                'verbose_name_plural': 'Товарные баннеры',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
