# Generated by Django 4.2.24 on 2025-09-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250914_1625'),
    ]

    operations = [
    ]
