# Generated by Django 4.2.24 on 2025-09-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_missing_fields'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE products_category ALTER COLUMN name DROP NOT NULL;
            ALTER TABLE products_category ALTER COLUMN description DROP NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE products_category ALTER COLUMN name SET NOT NULL;
            ALTER TABLE products_category ALTER COLUMN description SET NOT NULL;
            """
        ),
    ]
