# Generated by Django 4.2.24 on 2025-09-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250914_1647'),
    ]

    operations = [
    ]
