# Generated by Django 4.2.24 on 2025-09-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
