# Generated by Django 4.2.24 on 2025-09-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_make_category_name_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE products_tag ALTER COLUMN name DROP NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE products_tag ALTER COLUMN name SET NOT NULL;
            """
        ),
    ]
