# Generated by Django 4.2.24 on 2025-09-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20250914_1716'),
    ]

    operations = [
    ]
