# Generated by Django 4.2.24 on 2025-09-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_make_tag_name_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'RUB';
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS sku VARCHAR(100);
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0;
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) DEFAULT 0.0;
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS reviews_count INTEGER DEFAULT 0;
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS views_count INTEGER DEFAULT 0;
            ALTER TABLE products_product ADD COLUMN IF NOT EXISTS search_vector TSVECTOR;
            """,
            reverse_sql="""
            ALTER TABLE products_product DROP COLUMN IF EXISTS currency;
            ALTER TABLE products_product DROP COLUMN IF EXISTS sku;
            ALTER TABLE products_product DROP COLUMN IF EXISTS stock_quantity;
            ALTER TABLE products_product DROP COLUMN IF EXISTS is_active;
            ALTER TABLE products_product DROP COLUMN IF EXISTS rating;
            ALTER TABLE products_product DROP COLUMN IF EXISTS reviews_count;
            ALTER TABLE products_product DROP COLUMN IF EXISTS views_count;
            ALTER TABLE products_product DROP COLUMN IF EXISTS search_vector;
            """
        ),
    ]
