# Generated by Django 4.2.24 on 2025-09-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_create_favorite_table_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(related_name='products', to='products.shop', verbose_name='Магазины'),
        ),
    ]
