# Generated by Django 4.2.24 on 2025-09-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_product_fields'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE products_product ALTER COLUMN name DROP NOT NULL;
            ALTER TABLE products_product ALTER COLUMN description DROP NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE products_product ALTER COLUMN name SET NOT NULL;
            ALTER TABLE products_product ALTER COLUMN description SET NOT NULL;
            """
        ),
    ]
