# Generated by Django 4.2.24 on 2025-09-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_cartitem_category_commission_order_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
    ]
