# Generated by Django 4.2.24 on 2025-09-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_search_vector'),
    ]

    operations = [
    ]
