# Generated by Django 4.2.24 on 2025-09-15 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20250915_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_detected', models.BooleanField(default=False, verbose_name='Автоматически определена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.location', verbose_name='Локация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_locations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Локация пользователя',
                'verbose_name_plural': 'Локации пользователей',
                'unique_together': {('user', 'location')},
            },
        ),
    ]
