# Generated by Django 5.2.7 on 2025-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='featured_in_categories', to='products.product', verbose_name='Рекомендуемые товары'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_products',
            field=models.BooleanField(default=False, verbose_name='Есть товары'),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_menu_description',
            field=models.TextField(blank=True, verbose_name='Описание для мега меню'),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_menu_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение для мега меню'),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Путь'),
        ),
        migrations.AddField(
            model_name='category',
            name='products_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товаров'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active', 'category_level'], name='products_ca_parent__5aeee5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_level', 'sort_order'], name='products_ca_categor_a49bde_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['path'], name='products_ca_path_e3cf32_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['show_in_megamenu', 'is_active'], name='products_ca_show_in_f101b7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['has_products', 'is_active'], name='products_ca_has_pro_c6c749_idx'),
        ),
    ]
