# Generated by Django 5.2.7 on 2025-10-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_category_hierarchy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_mode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Цветовая модель'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла (байты)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='format',
            field=models.CharField(blank=True, max_length=10, verbose_name='Формат файла'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to='products/large/%Y/%m/%d/', verbose_name='Большой размер'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to='products/medium/%Y/%m/%d/', verbose_name='Средний размер'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/%Y/%m/%d/', verbose_name='Миниатюра'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='products_pr_product_e55bb9_idx'),
        ),
    ]
