# Generated by Django 5.2.7 on 2025-10-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_add_brand_field_to_product'),
    ]

    operations = [
    ]
